In [184]:
import numpy as np
import pandas as pd 

import matplotlib.pyplot as plt 

import torch
from torch import nn

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [185]:
iris = load_iris()
iris


{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [186]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [187]:
# Add target column
df['target'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [188]:
df.shape

(150, 5)

In [189]:
X = df.drop(columns='target')
y = df['target']

print(X[:2],"\n\n\n", y[:2])

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2 


 0    0
1    0
Name: target, dtype: int32


In [190]:
# Convert data to tensors
X = torch.from_numpy(X.values).double()
y = torch.from_numpy(y.values).long()


In [191]:
print(X.dtype, y.dtype)

torch.float64 torch.int64


In [192]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
len(X_train), len(y_train,), len(X_test), len(y_test)

(120, 120, 30, 30)

In [193]:
y.unique()

tensor([0, 1, 2])

In [194]:
# Define a model
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1= nn.Linear(in_features=4, out_features=10)
        self.layer2= nn.Linear(in_features=10, out_features=10)
        self.layer3= nn.Linear(in_features=10, out_features=3)
        
        self.relu = nn.ReLU()
        
    def forward(self, x):
        return self.layer3(self.relu(self.layer2(self.relu(self.layer1(x)))))
    
# Initialize model
model = MyModel()
model = model.double()
model
        

MyModel(
  (layer1): Linear(in_features=4, out_features=10, bias=True)
  (layer2): Linear(in_features=10, out_features=10, bias=True)
  (layer3): Linear(in_features=10, out_features=3, bias=True)
  (relu): ReLU()
)

In [195]:
# Define optimizer and loss function
loss_fn = nn.CrossEntropyLoss()
optimizer= torch.optim.SGD(params= model.parameters(), lr= 0.1)

In [196]:
print(X_train.dtype, y_train.dtype, X_test.dtype, y_test.dtype)

torch.float64 torch.int64 torch.float64 torch.int64


In [197]:
torch.manual_seed(42)
epochs = 10000
for epoch in range (epochs):
    
    # train loop
    model.train()
    y_preds = model(X_train)
    
    loss = loss_fn(y_preds, y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    
    # test loop
    model.eval()
    with torch.inference_mode():
        test_preds = model(X_test)
        test_loss = loss_fn(test_preds, y_test)
    
    if epoch % 1000 == 0:    
        print(f"Epoch: {epoch} | train loss: {loss} | test loss: {test_loss}")
        
    
    

Epoch: 0 | train loss: 1.104848540308873 | test loss: 1.0760240256885754


Epoch: 1000 | train loss: 0.09205376539204181 | test loss: 0.1213954063400879
Epoch: 2000 | train loss: 0.0618263251170742 | test loss: 0.07425700038009173
Epoch: 3000 | train loss: 0.05788217388756536 | test loss: 0.06011104495271924
Epoch: 4000 | train loss: 0.055448036933523896 | test loss: 0.05139386221804914
Epoch: 5000 | train loss: 0.050264205415330526 | test loss: 0.050844145890620585
Epoch: 6000 | train loss: 0.04576017587167087 | test loss: 0.04569526093414007
Epoch: 7000 | train loss: 0.045179840121470825 | test loss: 0.041845797902750316
Epoch: 8000 | train loss: 0.042916921353646074 | test loss: 0.038766397090455366
Epoch: 9000 | train loss: 0.041139138228135745 | test loss: 0.03535140463602241


In [198]:
# Make predictions

# Make predictions
model.eval()
with torch.inference_mode():
    y_preds = torch.argmax(torch.softmax(model(X_test), dim=1), dim=1) # Softmax because we have multi-class classification


    
y_preds[:10], y_test[:10]

(tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1]),
 tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1]))

<h1> <center> END